---
- name: Deploy a basic webserver
  hosts: web
  become: true
  vars:
    webserver_package: httpd
    webserver_service: httpd

  tasks:
  - name: Install webserver package
    package:
      name: "{{ webserver_package }}"
      state: present

  - name: Deploy the templated index file
    tags: [ template ]
    template:
      src: templates/index.html.j2
      dest: /var/www/html/index.html

  - name: Start and enable webserver
    service:
      name: "{{ webserver_service }}"
      state: started
      enabled: true
